### ISSUE TITLE
Adding `depends_on` in docker-compose.yml

### ISSUE THREAD

**Issue by cavo789** [alexandreelise/frankenphp-joomla#6]
To allow Docker to better understands dependencies, it's better to add a `depends_on` clause:

```yaml
version: '3.9'

services:

  joomla:
    [...]
+    depends_on:
+     - db

  db:
```

So Docker knows that the `joomla` service has a strong link with the `db` service.

See [https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) for more information.
